name: Github Pages

concurrency: 
  group: deployment
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: fonts-ipafont graphviz wget curl git
          version: 1.02
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openjdk-8-jre
          version: 1.02
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-latex-base
          version: 1.02
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install
        run: |
          sudo apt update
          sudo apt install texlive-xetex
      - name: build html
        run: |
          make html
      - name: build pdf
        run: |
          make pdf

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: generated

  deploy:
    environment:
      name: deployment
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
