name: Makefile CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install xetex
      run: sudo apt-get install texlive-xetex

    - name: Install plantuml
      run: sudo apt-get install plantuml

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build paper
      run: |
        make sequences.html \
        && make sequences.pdf

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: generated

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
