name: Makefile CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install xetex
      run: sudo apt-get install texlive-xetex

    - name: download, validate, install plantuml and its dependencies
      run: |
        curl -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2022.9/plantuml-1.2022.9.jar
        echo "8ca014b55d39707c2bb4cdec3686ba96995379d3  plantuml.jar" | sha1sum -c -
        mv plantuml.jar /opt/plantuml.jar
        mkdir -p "$HOME/.local/bin"
        echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> "$HOME/.local/bin/plantuml"
        chmod +x "$HOME/.local/bin/plantuml"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        sudo apt-get install -y graphviz

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build paper
      run: |
        make html \
        && make pdf

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: generated

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
