name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: nikeee/setup-pandoc@v1

    - name: Build paper
      run: make

    - name: Upload generated paper
      uses: actions/upload-artifact@v3
      with:
        path: generated/*
